app/app/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header="Talaba Baholash"
admin.site.site_title ="Talaba"
admin.site.index_title="Hush Kelibsiz"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pdfupload.urls')),
]

app/pdfupload/urls.py
from django.urls import path
from .views import Home, render_pdf_view, DetailView
app_name="pdfupload"
urlpatterns = [
    path("", Home, name='home'),
    path("detail/<str:id>/", DetailView, name="detail"),
    path('pdf/<str:pk>/',render_pdf_view ,name="pdf"),
]

app/pdfupload/models.py
from django.db import models

# Create your models here.


   
class Grops(models.Model):
    
    class Smester(models.TextChoices):
        BIR = "1", "1-semestr"
        IKKI = "2", "2-semestr"
        UCH = "3", "3-semestr"
        TURT = "4", "4-semestr"
        BESH = "5", "5-semestr"
        OLTI = "6", "6-semestr"
        YETTI = "7", "7-semestr"
        SAKKIZ = "8", "8-semestr"
        TUQQIZ = "9", "9-semestr"
        ON = "10", "10-semestr"
        
    class Fakultet(models.TextChoices):
        AMALIY_M_F = "AMALIY_M_F", "Amaliy matematika va fizika"
        BOSHLANGICH_T_GUMANITER_F = "2", "Boshlang\'ich ta'lim va gumaniter fanlar funkuteti"
        TABIY_FANLAR_F = "3", "Tabiy fanlar fakulteri"
        SANATSHUNOSLIK_FAKULTETE = "SANATSHUNOSLIK_FAKULTETE", "Sanatshunoslik fakul\'teti"
        JISMONIY_MADANIYAT_SPORT_VA_MK_TALIM = "JISMONIY_MADANIYAT_SPORT_VA_MK_TALIM", "Jismoniy madaniyat, sport va Maktabgacha ta'lim fakulteti"
        FILOLOGIYA_FAKULTETI = "FILOLOGIYA_FAKULTETI", "filologiya fakulteti"
    
    class Yunalish(models.TextChoices):
        # matematika va fizika
        M_VA_I_Y="M_VA_I_Y", "Matematika va informatika"
        F_VA_A_Y="F_VA_A_Y", "Fizika va astronomiya"
        # Boshlang'ich talim
        BOSH_TALIM_Y="BOSH_TALIM_Y", "Boshlang'ich ta'lim"
        TARIX_Y="TARIX_Y",  "Tarix "
        # Tabiy fanlar
        BIOLOGIYA ="BIOLOGIYA", 'Biologiya'
        GEOGRAFIYA_VA_IQTISODIY_B_y="GEOGRAFIYA_VA_IQTISODIY_B_y", "Geografiya va iqtisodiy bilim asoslari"
        KIMYO="KIMYO", 'Kimyo'
        
        # Sanatshinoslik Fakultiti
        MUSIQA_TA_Y="MUSIQA_TA_Y", "Musiqa ta'limi"
        TASVIR_S_Y="TASVIR_S_Y", "Tasviriy san'at muxandislik grafikasi"
        TEXNOLOGIK_T_F_K="TEXNOLOGIK_T_F_K", "Texnologik ta'lim Fakultet kvalifikatsiyasi"
        # Sport 
        JISMONIY_MAD="JISMONIY_MAD","Jismoniy madaniyat"
        SPORT_FAOLIYATI="SPORT_FAOLIYATI", "Sport faoliyati"
        MAKTABGACHA_TALIM="MAKTABGACHA_TALIM", "Maktabgacha ta'lim"
        # filogiya fakultet
        UZBEK_T_ADABIYOT="UZBEK_T_ADABIYOT", "O'zbek tili va adabiyoti"
        UZGA_TILLI_GRUHLARGA_RUS_T="UZGA_TILLI_GRUHLARGA_RUS_T", "O'zbek tilli guruhlarga rus tili"
        XORIJIY_TIL_ADABIYOTI_ING="XORIJIY_TIL_ADABIYOTI_ING","Xorijiy til va adabiyoti: ingliz tili"
                
    class Kafedra(models.TextChoices):
        TEXNOLOGIYA_T_k='TEXNOLOGIYA_T_Y', "TEXNOLOGIYA talim kafidrasi"
        RUS_TILI_ADABIYOT_K= 'RUS_TILI_ADABIYOT_K', 'Rus tili va adabiyoti kafedrasi'
        MATEMATIKA_VA_INFORMATIKA='MATEMATIKA_VA_INFORMATIKA', 'Matematika va Informatika'
        MAKTABGACHA_TALIM_K="MAKTABGACHA_TALIM_K", " Maktabgacha ta'lim kafidrasi"
        UZBEK_TILI_VA_ADABIYOTI_K='UZBEK_TILI_VA_ADABIYOTI_K', "o'zbek tili va adabiyoti kafedrasi"
        BOSHLANGICH_TALIM_K="BOSHLANGICH_TALIM_K", "Boshlang'ich talim nazariyasi kafedrasi"
        PEDAGOGIKA_K='PEDAGOGIKA_K', "Pedagogika kafedrasi"
        BOSHLANGICH_TALIM_METODIKASI_K="BOSHLANGICH_TALIM_METODIKASI_K", "Boshlang'ich talim metodikasi kafedrasi"
        PSIXOLOGIYA_K="PSIXOLOGIYA_K", 'Psixologiya kafedrasi'
        XORIJIY_TILLAR_K="XORIJIY_TILLAR_K","Xorijiy tillar kafedrasi"
        TASVIRIY_SANAT_VAmUHANDISLIK_K="TASVIRIY_SANAT_VAmUHANDISLIK_K", "Tasviriy san'at va muhandislik grafikasi kafidrasi"
        MUSIQA_TALIM_K="MUSIQA_TALIM_K", "Musiqa ta'lim kafedrasi"
        SPORT_TURLARINI_UQITISH_METO_K = 'SPORT_TURLARINI_UQITISH_METO_K', "Sport turlarini o'qitish metodikasi kafedrasi"
        KIMYO_K="KIMYO_K", "Kimyo kafedrasi"
        FIZIKA_ASTRONOMIYA_K="FIZIKA_ASTRONOMIYA_K","Fizika astronomiya kafedrasi"
        JISMONIY_MADANIYAT_NAZARIYASI_VA_MATEMATIKASI_K="JISMONIY_MADANIYAT_NAZARIYASI_VA_MATEMATIKASI_K","Jismoniy madaniyat nazariyasi va m,k"
        BIOLOGIYA_VA_GEOGRAFIYA_K="BIOLOGIYA_VA_GEOGRAFIYA_K", "Biologiya va Geografiya kafedrasi"
        IJTIMOIY_GUMANITAR_FANLAR_K="IJTIMOIY_GUMANITAR_FANLAR_K", 'Ijtimoiy gumanitar fanlar Kafedrasi'
        
    uquv_yil = models.CharField(max_length=25, verbose_name="o'quv yili") 
    smester = models.CharField(max_length=8, choices=Smester.choices, verbose_name="Semestr")
    yunalish=models.CharField(max_length=80, choices=Yunalish.choices, verbose_name="Yo'nalish")
    fakulteti = models.CharField(max_length=60, choices=Fakultet.choices, verbose_name="Fakulteti")
    kafedra = models.CharField(max_length=60, choices=Kafedra.choices, verbose_name="Kafedra")
    fan_nomi=models.CharField(max_length=200, verbose_name="Fan nomi")
    gruh_nomi=models.CharField(max_length=200, verbose_name="Guruh nomi")
    fan_soat =models.IntegerField()
    fan_kredit =models.CharField(max_length=25, blank=True, verbose_name="Fan krediti")
    
    def __str__(self) -> str:
        return self.gruh_nomi
    
    def save(self, *args, **kwargs):
        self.fan_kredit = str(int(self.fan_soat)/30)
        return super().save(*args, **kwargs)

class Talaba(models.Model):
    ism=models.CharField(max_length=250, verbose_name='Ismi')
    familya=models.CharField(max_length=250, verbose_name="Familyasi")
    ota=models.CharField(max_length=250, verbose_name="Otasining ismi")
    talaba_id=models.IntegerField(verbose_name="Talaba ID")
    gruh = models.ForeignKey(Grops, on_delete=models.CASCADE, verbose_name="Gruh")
    def __str__(self):
        return self.familya
    
class Talababaholash(models.Model):
    gruh = models.ForeignKey(Grops, on_delete=models.CASCADE, verbose_name="Gruh")
    talaba= models.ForeignKey(Talaba, on_delete=models.CASCADE, verbose_name="Talabalar")
    ball = models.IntegerField()
    bahosi = models.IntegerField(blank=True)
    uquv_boshqarma_boshligi=models.CharField(max_length=200, verbose_name="O'quv boshqarma boshlig'i", help_text="F.I.SH")
    oraliq_nazorat_masul = models.CharField(max_length=150, help_text="F.I.SH", verbose_name="Oraliq Nazorat Masuli")
    kafedra_mudiri=models.CharField(max_length=50, verbose_name="Kafedra mudiri")
    
    def __str__(self):
        return str(self.bahosi)
    
    def save(self, *args, **kwargs):
        if self.bahosi is None:
            if self.ball <=50 and self.ball>=45:
                self.bahosi = 5
            elif self.ball <45 and self.ball>=38:
                self.bahosi = 4
            elif self.ball <38 and self.ball>=30:
                self.bahosi = 3
            else:
                self.bahosi = 2
                
        return super(Talababaholash, self).save(*args, **kwargs)
    

app/pdfupload/views.py
from django.shortcuts import render
import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
from django.db.models import Q
from .models import Talababaholash, Talaba, Grops

# Create your views here.
def render_pdf_view(request, pk):
    
    talababaholash = Talababaholash.objects.get(pk=pk)
    template_path = 'index.html'
    context={'talababoholash': talababaholash}
    response = HttpResponse(content_type='application/pdf')
    
    response['Content-Disposition'] = 'attachment; filename="baxolash.pdf"'
    
    template = get_template(template_path)
    html = template.render(context)
    
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

def Home(request):
   grops=Grops.objects.all()
   return render(request, "hometo.html", {"grops":grops})

def Baholash(request, pk):
   talababaholash = Talababaholash.objects.get(pk=pk)
   return render(request, 'ditail.html', {})

def DetailView(request, id):
   grops=Grops.objects.get(id=id)
   talababaholash=grops.talababaholash_set.all()
   return render(request, "detail.html", {"talababaholash":talababaholash})

app/templates/_base.html
{% comment %} <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.0//EN" {% endcomment %}
    {% comment %} "http://www.w3.org/TR/xhtml-basic/xhtml-basic10.dtd"> {% endcomment %}
    <!DOCTYPE html >
{% load static %}
<html lang="en">
 
<head>

  <meta charset="UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> {% endcomment %}
    </head>

<body>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

app/templates/detail.html
{% extends "_base.html" %}

{% block content %}

ditail

{% for f in talababaholash %}
<a href="{% url "pdfupload:pdf" f.id %}"> Download</a>
{{f}}
{% endfor %}

{% endblock content %}

app/templates/home.html
{% extends "_base.html" %}

{% block content %}
<a href="{% url "pdfupload:pdffile" %}"> yuklash</a>






{% endblock content %}

app/templates/hometo.html
{% extends "_base.html" %}


{% block content %}

{% for gr in grops %}
<a href="{% url "pdfupload:detail" gr.id %}">
    {{gr.uquv_yil}}
    {{gr.gruh_nomi}}

</a>
{% endfor %}
{% endblock content %}

app/templates/index.html
{% include "_base.html" %}
{% load static %}
{% block content %}
<style type="text/css">

body{
  padding:0px;
  margin:0px;
  width: 100%;
  height: 100%;
  display:  flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}

.contaner{
  max-width: 1270px;
  display: flex;
  flex-direction: column;
  border: 1px solid red;
}
.text-center-bar{
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  gap:0px;
  padding: 1px;
}
.contaner .text-bir{
  padding:0px;
  margin:0px;
  font-size: 18px;
  text-align: center;
}

</style>
     <div class="contaner">
      <div class="text-center-bar">
    <p class='text-bir'>O'ZBEKISTON RESPUBLIKASI OLIY TA'LIM, FAN VA INNOVATSIYALAR VAZIRLIGI</p>
    <p class='text-bir'>O'zbekiston-Finlandiya pedagogika instituti</p>
    <p class='text-bir'>BAHOLASH QAYDNOMASI N%__________</p>
      </div>
    <p style=" padding:0px; margin:0px; font-size: 15px;">Fakultet nome:<b> {{grops.yunalish.fakultet.name}}</b></p>
    <p style=" padding:0px; margin:0px; font-size: 15px;">Ta'im yo'nalishi (mutaxassislik) nome:<b> {{grops.yunalish}}</b></p>

    <p style=" padding:0px; margin:0px; font-size: 15px;"> O'qov yili:<b> {{grops.uqov_yil}} </b>o'qov yili<b> {{grops.smester}}</b> semester  {{ grops.name}}</b> - guruh</p>
    {% for f in talababoholash|slice:":1"%}
    <p style=" padding:0px; margin:0px; font-size: 15px;"> Fan nome :<b> {{f.fan.fan_nome }}</b></p>
    <p style=" padding:0px; margin:0px; font-size: 15px;">Fan o'qitovchilari: <b>{{f.fan.teacher}}</b></p>
   
    <p style=" padding:0px; margin:0px; font-size: 15px;"> Semestrda danga ajratilgan umumiy soadtlar/kredit: <b>{{f.fan.fan_soat}} /{{f.fan.fan_kredit}}</b></p>
    <p style=" padding:0px; margin:0px; font-size: 15px;"> Oraliq nazorat/qayta topshirish o'tkazilgan sana: sana <b>5515424</b></p>
    <div style=" width:100%;">
       {% endfor %}
       <a>hi</a>
      <table class="table" style="border:1px solid black; width:100%">
          <tr style="height:30px">
            <th style="width:5%" scope="col">N%</th>
            <th style="width:40%" scope="col">Talaba familiyasi, ismi, otasining ismi</th>
            <th style="width:13%">Talaba ID raqami</th>
            <th style="width:25%" scope="col">To'plangan ball Maksimal ball - 50 Minimal ball - 30</th>
            <th style="width:17%; text-align: center;" scope="col">Talabaning bahosi</th>
          </tr>
          {% for talabab in talababoholash %}
          <tr style="height:18px">
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ talabab.talaba.ism }} {{ talabab.talaba.familya }} {{ talabab.talaba.ota }}</td>
            <td>{{talabab.talaba.talaba_id}}</td>
            <td>{{talabab.ball}}</td>
            <td>{{talabab.bahosi}}</td>
          </tr>
          {% endfor %}
      </table>
      </div>
      <div>
        <p style=" padding:0px; margin:7px 0px 0px 0px; font-size: 15px;">Jami talaba: {{grops.talababaholash_set.all.count}}, shundan, 5:___ , 4:____ , 3:____ , 2:_____, Kelmadi:____</p>
        
        <p style=" padding:0px; margin:0px; font-size: 15px;">Fakultet dekan {{grops.yunalish.fakultet.dekan }}</p> 
        {% for tk in talababoholash|slice:":1" %}
        <p style=" padding:0px; margin:0px; font-size: 15px;" >Kafedra mudiri  {{tk.kafidra_m.ism}}</p><p>{{ tk.or_nazorat_masul}}</p>
        
        <p style=" padding:0px; margin:0px; font-size: 15px;"> Ro'yxatga olindi: N%______  Sana: ____________</p>
        <p style=" padding:0px; margin:0px; font-size: 15px;"> O'qov-uslubiy boshqarma boshlig'i {{tk.uquv_boshqarma_boshligi}}</p>
        {% endfor %}
    </div>
{% endblock content %}